use std::{
    fmt, fs,
    fs::File,
    path::{Path, PathBuf},
    sync::{Arc, Mutex},
};

use milkdrift_persistence::{PersistenceError, TimestampMillis};
use redb::Database;

use crate::{
    error,
    fault::{FaultInjector, no_faults},
    schema::{
        APPLICATION_COLD_RECEIPT_COUNT_KEY, APPLICATION_COMMAND_RECEIPTS_COLD,
        APPLICATION_COMMAND_RECEIPTS_HOT, APPLICATION_HOT_RECEIPT_COUNT_KEY,
        APPLICATION_HOT_RECEIPTS_BY_COMPLETION, APPLICATION_LAYOUTS, APPLICATION_PROPOSALS,
        APPLICATION_RECEIPT_ARCHIVE_GENERATION_KEY, APPLICATION_RECEIPT_LAST_ARCHIVED_AT_KEY,
        ARTIFACT_ACCOUNTING, ARTIFACT_DELETE_GUARDS, ARTIFACT_DIGEST_RESERVATIONS,
        ARTIFACT_MANIFEST, ARTIFACT_METADATA, ARTIFACT_PATHS, ARTIFACT_PUBLICATIONS,
        ARTIFACT_PUBLICATIONS_BY_AGE, ARTIFACT_REFERENCES, ARTIFACT_RESERVATIONS,
        ARTIFACT_TEMP_MANIFEST, ARTIFACT_TEMP_OWNERS, ARTIFACTS_BY_DIGEST, COMMAND_RESULTS,
        EVENT_HISTORY_DIGESTS, INTERNAL_DOCUMENT_FORMAT_VERSION,
        INTERNAL_DOCUMENT_FORMAT_VERSION_KEY, LEASE_ENTRIES, LEASE_INDEX, LEASE_SET_REVISION_KEY,
        METADATA, NONTERMINAL_RUNS, NONTERMINAL_SET_COUNT_KEY, PEER_ACTIVE_CLAIMS, PEER_CATALOGS,
        PEER_DISPATCH_AVAILABLE, PEER_EXECUTION_ACCOUNTING, PEER_EXECUTION_GLOBAL_ACCOUNTING_KEY,
        PEER_EXECUTION_LOCATIONS, PEER_EXECUTION_TOMBSTONES, PEER_EXECUTIONS,
        PEER_EXECUTIONS_BY_REQUEST, PEER_OBSERVATION_ARTIFACTS, PEER_OBSERVATIONS,
        PEER_RELATIONSHIPS, PEER_TERMINAL_INDEX, REVISIONS, REVISIONS_BY_DIGEST, ROOT_SCOPES,
        RUN_ARTIFACT_OWNERSHIP, RUN_EVENTS, RUN_HEADS, RUN_HISTORY_HEADS, RUN_SUMMARIES,
        RUNNABLE_ENTRIES, RUNNABLE_INDEX, RUNNABLE_RUN_HEADS, SCHEMA_VERSION_KEY, SCOPES,
        SECURITY_AUDIT, SECURITY_AUDIT_COUNT_KEY, SECURITY_AUDIT_NEXT_SEQUENCE_KEY,
        SIGNAL_RECEIPTS, SNAPSHOT_LATEST, SNAPSHOTS, STORAGE_SCHEMA_VERSION, TIMER_ENTRIES,
        TIMER_INDEX, VALUES, WORKSPACE_BUDGETS, WORKSPACE_USAGE, WORKSPACE_VALUE_HEADS,
    },
};

mod config;
mod filesystem;
mod open;
mod schema;

pub(crate) use config::{ARTIFACT_DIRECTORY, DATABASE_FILENAME, TEMP_DIRECTORY};
pub use config::{ArtifactClock, RedbStore, RedbStoreConfig, SystemArtifactClock};
pub(crate) use filesystem::{
    ensure_regular_file_or_absent, prepare_owned_directory, sync_owned_directory,
};
pub(crate) use schema::{initialize_schema, validate_schema};
